# Generated by Django 5.2.4 on 2025-08-16 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('subject', models.CharField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_Type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('services', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tranning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_Type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=100)),
                ('owner_name', models.CharField()),
                ('contact_number', models.IntegerField()),
                ('services', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='walking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=100)),
                ('owner_name', models.CharField()),
                ('contact_number', models.IntegerField()),
                ('Address', models.TextField()),
                ('prefered_Time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=100)),
                ('time', models.TimeField()),
                ('Duration', models.CharField(choices=[('15 Min', '15Min '), ('30Min', '30Min'), ('45Min', '45Min'), ('1hr', '1hr'), ('2hr', '2hr')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcare.pet_doctor')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
