# Generated by Django 5.2.4 on 2025-08-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
